Обновил файл с заданием
rstu-web-labs/Lab-1_DB_and_legacy pull request #1
Opened 2024-02-12 12:07 UTC by Kzefnde

2024-02-13 13:12 UTC, kapkaevandrey requested changes
Не хвататет скриптов, и имя PR измени.

2024-02-13 13:12 UTC, kapkaevandrey commented on src/лаба1.sql
> +    color VARCHAR(50) NOT NULL
Цвета можно вынести в отдельную таблицу

2024-02-13 13:12 UTC, kapkaevandrey commented on src/лаба1.sql
> +    brand VARCHAR(50) NOT NULL,
Бренды лучше вынести в отдельную таблицу, и модели с параметрами модели в отдельную.

2024-02-14 17:36 UTC, Kzefnde commented on src/лаба1.sql
> +    brand VARCHAR(50) NOT NULL,
Здравствуйте,обновил файл с заданием

2024-02-17 17:28 UTC, kapkaevandrey requested changes

2024-02-17 17:28 UTC, kapkaevandrey commented on src/лаба1.sql
> +);
Страны потерялись

2024-02-17 18:25 UTC, Kzefnde commented on src/лаба1.sql
> +);
добавил страны в эту таблицу и поправил загрузку данных в неё (каюсь ошибка тупая была :D )

2024-02-20 08:45 UTC, kapkaevandrey requested changes
Там есть ошибка синтаксиса, и не создаётся схема car_shop. Решение норм, но проверьте, что всё это запускается.

2024-02-20 08:45 UTC, kapkaevandrey commented on src/лаба1.sql
> +    name VARCHAR(50) NOT NULL -- Название бренда
Ошибка синтаксиса, не хватает запятой

2024-02-20 09:50 UTC, Kzefnde commented on src/лаба1.sql
> +    name VARCHAR(50) NOT NULL -- Название бренда
добавил запятую,теперь всё нормально работает

2024-02-23 10:47 UTC, kapkaevandrey requested changes
Надо починить.

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +);
gasoline потерялся

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    color VARCHAR(50) -- Цвет автомобиля
Подумайте, что будет если заказчик решит хранить в таблцие код цвета помимо названия.

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    discount SMALLINT, -- Размер скидки в процентах
Скидка может быть не целым числом. Подумайте над numeric и проверкой этого значения

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    raw_data.sales;
Не стоит использовать сырые данные.

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    raw_data.sales s
Не стоит использовать сырые данные.

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    raw_data.sales s
Не стоит использовать сырые данные.

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    raw_data.sales s
Не стоит использовать сырые данные.

2024-02-23 10:47 UTC, kapkaevandrey commented on src/лаба1.sql
> +    raw_data.sales
Не стоит использовать сырые данные.

2024-02-23 12:31 UTC, Kzefnde commented on src/лаба1.sql
> +    color VARCHAR(50) -- Цвет автомобиля
А как мне хранить код цвета,когда в таблице есть только название цвета?

2024-02-26 17:06 UTC, kapkaevandrey commented on src/лаба1.sql
> +    color VARCHAR(50) -- Цвет автомобиля
Ну вот я об этом, может лучше вынести цвет в обычную таблицу? Тогда хранение всей этой информации будет очень удобным.

2024-02-26 17:09 UTC, kapkaevandrey approved these changes
Хорошее решение

2024-02-26 17:10 UTC, kapkaevandrey commented
Хорошее решение

2024-02-26 17:10 UTC, closed without merging