asb036/bondar
rstu-web-labs/Lab-1_DB_and_legacy pull request #18
Opened 2024-02-19 16:51 UTC by Sem1onBondar

2024-02-20 08:22 UTC, kapkaevandrey requested changes
У вас дата потерялась. Скрипт не работает. Подумайте над ограничениями для данных.
Данные хорошо нормализованны.

2024-02-20 08:22 UTC, kapkaevandrey commented on src/Lab_1.sql
> +        CHECK (brand_origin IN ('Russia', 'Germany', 'South Korea', 'USA'))
Хорощо, но могут добавиться другие страны. Китай например, в данном случае проверка избыточна

2024-02-20 08:22 UTC, kapkaevandrey commented on src/Lab_1.sql
> +    brand_origin varchar(55)
Можно повесить уникальность

2024-02-20 08:22 UTC, kapkaevandrey commented on src/Lab_1.sql
> +    name_color varchar(55)
Также можно добавить уникальность

2024-02-20 08:22 UTC, kapkaevandrey commented on src/Lab_1.sql
> +    gasoline_consumption numeric(4,2) CHECK (gasoline_consumption < 100),
Тут лучше сделать BETWEEN 0 and 100

2024-02-20 08:22 UTC, kapkaevandrey commented on src/Lab_1.sql
> +    CONSTRAINT fk_constraint_brand FOREIGN KEY (id_brand)
не хватает ON DELETE

2024-02-20 08:22 UTC, kapkaevandrey commented on src/Lab_1.sql
> +CREATE TABLE raw_data.sales (
У вас дата потерялась

2024-02-20 16:27 UTC, Sem1onBondar commented on src/Lab_1.sql
> +CREATE TABLE raw_data.sales (
Всё, что выше указано, подправил

2024-02-21 10:38 UTC, kapkaevandrey approved these changes
Можно было и лучше.

2024-02-21 10:38 UTC, kapkaevandrey commented on src/Lab_1.sql
> +    CONSTRAINT fk_constraint_brand FOREIGN KEY (id_brand)
А если бренд удалят то всё удалять придётся?

2024-02-21 10:38 UTC, kapkaevandrey commented
Выполнено

2024-02-21 10:38 UTC, closed without merging