Asb37/borovinscky
rstu-web-labs/Lab-1_DB_and_legacy pull request #54
Opened 2024-02-26 12:03 UTC by Katabym

Upload sql script

2024-02-26 16:18 UTC, kapkaevandrey requested changes
Данные не нормализованы, но вы близки к победе. Подумайте какие поля могут быть уникальными и не забудьте про подведение данных при удалении внешних ключей.

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  color VARCHAR(20) -- символьный тип для названия цвета
UNIQUE?

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  country_name VARCHAR(20) -- символьный тип для названия страны
UNIQUE? Кстати, что насчёт названия "Соединенное Королевство Великобритании и Северной Ирландии" 59 символов

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  model VARCHAR(15), -- символьный тип для названия модели
Тут не хватает ссылки на бренд

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  gasoline_consumption float4, -- вещественный тип для расхода топлива
Эта штука скорее относится к описанию модели.

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  discount INTEGER, -- целочисленный тип для скидки
Скидка может быть не цело численной.

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  CONSTRAINT fk_model_id FOREIGN KEY (model_list_id) REFERENCES models_list (model_id),
ON DELETE ?

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +    (SELECT id FROM colors WHERE color = split_part(substring(auto from '[^,]+$'), ' ', 2)),
Ой ей два подзапроса, может получиться обойтись без них?

2024-02-26 16:18 UTC, kapkaevandrey commented on src/scripts.sql
> +  model VARCHAR(15), -- символьный тип для названия модели
Ошбка синтаксиса.

2024-02-26 17:58 UTC, Katabym commented on src/scripts.sql
> +  gasoline_consumption float4, -- вещественный тип для расхода топлива
блин, так и знал, зря переделывал

2024-03-03 21:25 UTC, kapkaevandrey requested changes
Ещё немного, ещё чуть чуть.

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +  person_name VARCHAR(100) UNIQUE,  -- символьный тип для имени
Вот тут не факт, прямо очень не факт.

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +  color VARCHAR(30)  -- символьный тип для названия цвета
Это поле уникальное.

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +  country_name VARCHAR(70) UNIQUE  -- символьный тип для названия страны
Отлично

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +  gasoline_consumption float4 -- вещественный тип для расхода топлива
Здесь отлично подойдёт DECIMAL(5, 2)

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +);
Если при удалении мы проставим NULL то потеряем вообще всю информацию о машине. Так же очень странно здесь смотрится внешний ключ на модель и бренд. Скорее ссылка на бренд должна быть в модели автомобиля. Добавьте сюда ещё цвет и таблица ниже вообще не понадобиться.

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +  CONSTRAINT fk_sold_car_id FOREIGN KEY (sold_car_id) REFERENCES cars_eque (car_eque_id) ON DELETE SET NULL,
SET NULL, а что продавали тогда?

2024-03-03 21:25 UTC, kapkaevandrey commented on src/scripts.sql
> +  constraint fk_brand_country_id foreign key (brand_country_id) REFERENCES country (country_id)ON DELETE SET NULL
Тут есть проблемка, вы не указали схему для таблицы **country** а значит она будет искаться в public а там её и нет.

2024-03-08 11:23 UTC, kapkaevandrey approved these changes
Есть замечания но сойдёт. Хотя такое в прод пока нельзя, будут проблемы. Да и от подзапросов, стоит всегда по возможности избавляться.

2024-03-08 11:23 UTC, kapkaevandrey commented on src/scripts.sql
> +  brand_name VARCHAR(20) UNIQUE, -- символьный тип для названия бренда
Здесь опасно, нет гарантии что у вас не будет два одноимённых бренда из разных стран.
Здесь отлично подошёл был UNIQUE(brand_name, brand_country_id )

2024-03-08 11:23 UTC, kapkaevandrey commented on src/scripts.sql
> +  CONSTRAINT fk_model_id FOREIGN KEY (model_list_id) REFERENCES car_shop.models_list (model_id)ON DELETE SET NULL,
Лучше конечно было сделать RESTRICT

2024-03-08 11:23 UTC, kapkaevandrey commented on src/scripts.sql
> +  model VARCHAR(15) unique,  -- символьный тип для названия модели
Малова-то, лучше конечно погуглить самое длинное название модели автомобиля.

2024-03-08 11:23 UTC, kapkaevandrey commented
Есть замечания

2024-03-08 11:23 UTC, closed without merging