Asb037/gusko
rstu-web-labs/Lab-1_DB_and_legacy pull request #60
Opened 2024-02-26 22:35 UTC by LastDayWithLess

2024-03-03 19:11 UTC, kapkaevandrey requested changes
Надо переработать структуру таблицы.

2024-03-03 19:11 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +color varchar(20) null
может быть уникальным.

2024-03-03 19:11 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +marka varchar(30) not null
может быть уникальным

2024-03-03 19:11 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +);
Сюда стоило добавить внешний ключ на бренд и сюда же вынести потребление топлива.

2024-03-03 19:11 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +idColor int not null references car_shop.colors(idColor),
везде не хватает описания ON DELETE

2024-03-03 19:11 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +create table if not exists car_shop.auto (
Уже видел у кого-то такое решение, данные должны быть связаны по смыслу, зачем в продаже фигурирует страна, когда она относится к бредну, и зачем продажи вынесены в отдельную таблицу? По идее продажа это что купили, кто купил, когда купил, цена и скидка. Пять полей.

2024-03-08 11:16 UTC, kapkaevandrey requested changes
Надо поправить(

2024-03-08 11:16 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +country varchar(60) null
А зачем нам хранить пустые записи в таблице?

2024-03-08 11:16 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +color varchar(20) unique null
А зачем нам пустые записи в таблице?

2024-03-08 11:16 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +);
По прежнему замечание не закрыто. Для numeric следует определить границы точности. Вы уверены что значение потребления топлива будет уникальными для всех марок в рамках одной таблицы?

2024-03-08 11:16 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +idCars int not null references car_shop.cars(idCars) ON DELETE CASCADE,
Вы уверены, что нужен CASCADE получиться при удалении из базы машины, все данные о продажах тоже будут удалены?

2024-03-08 11:16 UTC, kapkaevandrey commented on solution lab_1/normalBD.sql
> +join car_shop.sales s2 on s.price  = s2.price and s."date" = s2."date"
; потерялась, не запускается(

2024-03-08 11:56 UTC, LastDayWithLess commented on solution lab_1/normalBD.sql
> +idCars int not null references car_shop.cars(idCars) ON DELETE CASCADE,
Да, так и планировалось

2024-03-13 09:56 UTC, kapkaevandrey requested changes

2024-03-13 09:56 UTC, kapkaevandrey commented on solution lab_1/NormalDB.sql
> +idMarka int not null references car_shop.marks(idMarka) ON DELETE CASCADE,
Почему же всё таки марка здесь? Ведь она логически относится к модели и логично ссылка на марку должны быть там. CASCADE в данном случае плохая идея, т.к. приведёт к удалению всех объектов и потянет за собой, удаление платежей.

2024-03-13 09:56 UTC, kapkaevandrey commented on solution lab_1/NormalDB.sql
> +from raw_data.sales
Не допустимо использовать сырые данные в аналитических скриптах.

2024-03-24 07:50 UTC, kapkaevandrey approved these changes
Сойдёт структура не сильно удобно нормализована, но в целом.

2024-03-24 07:51 UTC, closed without merging