Kovalchuk lab1 complete
rstu-web-labs/Lab-1_DB_and_legacy pull request #70
Opened 2024-02-28 06:33 UTC by a1ehanJS

2024-03-03 18:27 UTC, kapkaevandrey requested changes
Чуть чуть и будет норм.

2024-03-03 18:27 UTC, kapkaevandrey commented on src/Script.sql
> +  on delete cascade
Опасно, удаление страны потянет за собой удаление бренда, а дальше модель и затем продажи, т.е. из базы исчезнет запись о финансовой операции. Ой ёй, верните деньги.

2024-03-03 18:27 UTC, kapkaevandrey commented on src/Script.sql
> +  gasoline_consumption DECIMAL
Хорошо, но стоит описать точность числа, что бы уменьшить расходы на производительность и память.

2024-03-03 18:27 UTC, kapkaevandrey commented on src/Script.sql
> +COPY sales --скопировали данные файла в таблицу сырых данных
Надо указать схему иначе данные полетят в схему public а там такой таблицы нет.

2024-03-05 11:05 UTC, a1ehanJS reviewed
исправил 1 лабу

2024-03-05 11:07 UTC, a1ehanJS commented
fixed

2024-03-08 10:27 UTC, kapkaevandrey approved these changes
Есть небольшой баг, но  в остальном всё норм.

2024-03-08 10:27 UTC, kapkaevandrey commented on src/Script.sql
> +  brand_name VARCHAR(50) not null unique,--unique гарантирует уникальность данных
Опасно, есть вероятность, что у вас будет два одноимённых бренда из разных стран.

2024-03-08 10:27 UTC, kapkaevandrey commented
Хорошо.

2024-03-08 10:27 UTC, closed without merging