Лаба1 сделана
rstu-web-labs/Lab-1_DB_and_legacy pull request #81
Opened 2024-02-29 19:31 UTC by krokn

2024-03-03 17:59 UTC, kapkaevandrey requested changes
Выглядит неплохо, но нужно поправить ошибки.

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +  name_country varchar(11)
11 ? Маловато будет, стоит погуглить максимально длинное название страны.

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	color varchar(20) not null
20 точно хватит? может сделать это поле уникальным?

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +CREATE TABLE car_shop.counry (
counTry

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	id_brand integer references car_shop.brand (id_brand),
ON DELETE? Также вы ссылаетесь на таблицу которая будет создана чуть ниже. Скрипт целиком, не сработает.

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	gasoline_consumtion decimal check (gasoline_consumtion < 10)
А потребление может быть отрицательным? Также если вы используете decimal не забудьте указать границы размера цифры. Стоит погуглить прожорливость различных марок автомобилей.

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	brand_name varchar(30) not null
Это поле может быть уникальным? А может уникальными сделать сочетание страна и имя бренда?

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	id_counry integer references car_shop.counry (id_brand_origin),
ON DELETE?

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	price decimal not null,
Размеры decimal

2024-03-03 17:59 UTC, kapkaevandrey commented on src/Script.sql
> +	discount integer
Скидка может быть не целым числом, 10,5 % к примеру, мы же машины продаём, а не хлеб.

2024-03-06 06:31 UTC, krokn reviewed
Исправил

2024-03-08 10:13 UTC, kapkaevandrey approved these changes
Есть замечания и их стоит внимательно обудмать( В целом работа принмается

2024-03-08 10:13 UTC, kapkaevandrey commented on src/result.sql
> +  id_brand_origin serial primary key not null,
На самом деле **primary key** уже накладывает ограничение **not null** и **unique**

2024-03-08 10:13 UTC, kapkaevandrey commented on src/result.sql
> +	id_country integer unique references car_shop.country (id_brand_origin)
Упс, у вас может быть два бренда из одной страны( Ой ей.
Здесь лучше сделать UNIQUE(id_country, brand_id) как ограничение на уникальность комбинации.

2024-03-08 10:13 UTC, kapkaevandrey commented
С замечаниями, но  принято.

2024-03-08 10:13 UTC, closed without merging