Lab1
rstu-web-labs/Lab-1_DB_and_legacy pull request #9
Opened 2024-02-16 14:00 UTC by navvidu

2024-02-17 17:26 UTC, kapkaevandrey requested changes
Стоит пересмотреть структуру таблиц, к примеру в вашей таблице car_shop.auto отсутствуют внешние ключи, хотя ниже вы начинаете создавать подобные таблицы. Также для всех внешних ключей подумайте о том какие CONSTRAINTS могут вам понадобиться.

Также продумайте как можно выделить данные чтобы они не дублировались,

2024-02-17 17:26 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +CREATE TABLE car_shop.colors ( -- таблица цветов авто
Удобней сделать просто таблицу цветов, на которую будет ссылаться запись в таблице конкретного автомобиля.

2024-02-17 17:26 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    gasoline_consumption DECIMAL(5,2),
Этот показатель относится к марке автомобиля, почему он в продажах?

2024-02-20 08:31 UTC, kapkaevandrey requested changes
Ошибка в 4 скрипте, проверьте точность вывода данных.

2024-02-20 08:31 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    name VARCHAR(255)-- имя символьное значение
Можно сделать уникальным

2024-02-20 08:31 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    name VARCHAR(255) NOT NULL-- имя символьное значение
Можно сделать уникальным

2024-02-20 08:31 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    origin_id INTEGER REFERENCES car_shop.origins(id) ON DELETE cascade
А что произойдёт с записями который сслаются на эту запись. В данном случае лучше повесить RESTRICT

2024-02-20 17:19 UTC, navvidu commented
Уникальность добавила. Запрос стал показывать корректную информацию

2024-02-23 10:43 UTC, kapkaevandrey requested changes
Надо починить. Проверьте точность расчётов в 5 скрипте, там что-то не так с определением максимальной цены продажи по США.

2024-02-23 10:43 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    name VARCHAR(255) unique -- имя символьное уникальное
NOT NULL?

2024-02-23 10:43 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    origin_id INTEGER REFERENCES car_shop.origins(id) ON DELETE RESTRICT
Отлично

2024-02-23 10:43 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    auto_id INTEGER REFERENCES car_shop.auto(id) ON DELETE CASCADE,
Ой ёй, данные о продажах удалять не стоит, там где деньги там опасность.)))) Подумайте над запретами.

2024-02-23 10:43 UTC, kapkaevandrey commented on src/life_of_wheels.sql
> +    FROM raw_data.sales r
Не стоит использовать сырые данные, аналитические скрипты должны использоваться вместе с новой структурой

2024-02-23 11:19 UTC, navvidu commented
В 4 не те данные попали, не знаю почему. Я несколько вариантов пробовала, видимо, случайно сохранила. Переделала. А в 5 скрипте без учета скидки, так и входит, что 79тыс это максимальная цена продажи. Скрипт верно показывал. В остальных случаях он добавляет к прайсу еще сумму, которую вычла скидка.
![photo_2024-02-15_14-26-44](https://github.com/rstu-web-labs/Lab-1_DB_and_legacy/assets/118108694/bc213f55-9fc0-4c0f-bf3c-2878b0be1663)
![photo_2024-02-15_14-26-44 (2)](https://github.com/rstu-web-labs/Lab-1_DB_and_legacy/assets/118108694/d8bbe9d8-dd3c-4c7b-b2aa-31af572aee4b)

2024-02-23 11:25 UTC, navvidu commented
В 4 не то сохранение попало. Я несколько вариантов пробовала, видимо, случайно сохранила. Переделала. А 5 скрипт по-другому переписала, но там без учета скидки, так и входит, что 79тыс это максимальная цена продажи. Скрипт верно показывал. В остальных случаях он добавляет к прайсу еще сумму, которую вычла скидка.

2024-02-23 11:38 UTC, navvidu commented
Все, что могла, то испарвила. 4 по-другому способу не получается сделать(( вывод некорректный иначе. А 5 скрипт по-другому переписала, но там без учета скидки, так и входит, что 79тыс это максимальная цена продажи. В остальных случаях он добавляет к прайсу еще сумму, которую вычла скидка.

2024-02-24 09:21 UTC, navvidu commented
Исправила, что могла. В 4 не выходит другим способом(( вывод некорректный.

2024-02-26 16:54 UTC, kapkaevandrey approved these changes
Есть замечания, но в целом неплохо.

2024-02-26 16:55 UTC, kapkaevandrey commented
Выполнено.

2024-02-26 16:55 UTC, closed without merging